version: '3.8'

#for normal run " docker-compose up -d " for database backup (includes normal) run " docker-compose --profile backup up -d "

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: footballticket-frontend:latest
    container_name: footballticket-frontend
    ports:
      - "3000:80"
    networks:
      - footballticket_network
    depends_on:
      - backend
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        parallelism: 1
      rollback_config:
        parallelism: 1
        failure_action: pause
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ../football-ticketindv
      dockerfile: Dockerfile
    image: football-ticketindv:latest
    container_name: footballticket-backend-staging
    ports:
      - "8091:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    networks:
      - footballticket_network
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        order: stop-first
        failure_action: rollback
        parallelism: 1
      rollback_config:
        parallelism: 1
        failure_action: pause
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mysql:latest
    container_name: footballticket_db
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=footballticket
      - MYSQL_ALLOW_EMPTY_PASSWORD=true 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=your_secure_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - footballticket_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      update_config:
        failure_action: rollback

  db-backup:
    image: mysql:latest
    container_name: footballticket_db_backup
    volumes:
      - mysql_backups:/backups
      - ./backup-script:/backup-script
    networks:
      - footballticket_network
    depends_on:
      - db
    command: >
      /bin/bash -c "
      echo '#!/bin/bash
      timestamp=$$(date +%%Y%%m%%d_%%H%%M%%S)
      mysqldump -h footballticket_db -u root footballticket > /backups/backup_$$timestamp.sql
      find /backups -type f -mtime +7 -delete' > /backup-script/backup.sh &&
      chmod +x /backup-script/backup.sh &&
      /backup-script/backup.sh"
    profiles:
      - backup

networks:
  footballticket_network:
    name: footballticket_network

volumes:
  mysql_data:
  mysql_backups: